# Flyway pipeline db2Z community edition

trigger:
- feature/db2z

pool:
  name: DPS

steps:
- task: Bash@3
  displayName: 'set env BUILD_JDK to $JAVA_HOME'
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=BUILD_JDK]$JAVA_HOME"'
- task: Bash@3
  displayName: 'Print environment variables'
  inputs:
    targetType: 'inline'
    script: printenv | sort

# Haal ergens in dit proces de java code door de SonarQube controles heen
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    # publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false

- task: Bash@3
  displayName: 'Remove previous Flyway jars from runtime'
  inputs:
    targetType: inline
    script: 'rm -f $FLYWAY_RUNTIME_LIB/*jar'

- task: Bash@3
  displayName: 'Copy Flyway jars from target to runtime'
  inputs:
    targetType: inline
    script: 'cp $(Build.Repository.LocalPath)/*/target/*.jar $FLYWAY_RUNTIME_LIB'
- task: Bash@3
  displayName: 'Do a Flyway test with the new jars'
  inputs:
    targetType: inline
    script: 'flyway -X migrate -configFiles=$FLYWAY_CONF -createSchemas="false" -schemas="ZDQO01" -baselineOnMigrate=true || exit 1'
    

